# Generated by Django 5.2.3 on 2025-06-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_job_job_type_userprofile_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.CharField(max_length=100),
        ),
    ]
