# Generated by Django 5.2.3 on 2025-06-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Shortlisted'), ('R', 'Rejected')], default='P', max_length=1),
        ),
    ]
